apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ [namespace, sonarqube_deploy_suffix_name]|join('-') }}"
  namespace: "{{ namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: "{{ [namespace, sonarqube_deploy_suffix_name]|join('-') }}"
  template:
    metadata:
      labels:
        run: "{{ [namespace, sonarqube_deploy_suffix_name]|join('-') }}"
    spec:
      containers:
      - env:
        - name: SONARQUBE_WEB_JVM_OPTS
          value: -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dh2.bindAddress=127.0.0.1
        image: "{{ sonarqube_image }}"
        imagePullPolicy: Always
        name: "{{ [namespace, sonarqube_deploy_suffix_name]|join('-') }}"
        ports:
        - containerPort: 9092
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
