---
- name: create Gitlab service
  command: kubectl expose deployment "{{ [namespace, gitlab_deploy_suffix_name]|join('-') }}"
    --type=NodePort  --namespace="{{ namespace }}"
  listen: "create gitlab service"
  ignore_errors: True

- name: create Jenkins service
  command: kubectl expose deployment "{{ [namespace, jenkins_deploy_suffix_name]|join('-') }}"
    --type=NodePort  --namespace="{{ namespace }}"
  listen: "create jenkins service"
  ignore_errors: True

- name: create Sonarqube service
  command: kubectl expose deployment "{{ [namespace, sonarqube_deploy_suffix_name]|join('-') }}"
    --type=NodePort   --namespace="{{ namespace }}"
  listen: "create sonarqube service"
  ignore_errors: True

- name: create Nexus service
  command: kubectl expose deployment "{{ [namespace, nexus_deploy_suffix_name]|join('-') }}"
    --type=NodePort   --namespace="{{ namespace }}"
  listen: "create nexus service"
  ignore_errors: True
