apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: white-sonarqube 
  namespace: white
spec:
  replicas: 1
  selector:
    matchLabels:
      run: white-sonarqube 
  template:
    metadata:
      labels:
        run: white-sonarqube 
    spec:
      containers:
      - env:
        - name: SONARQUBE_WEB_JVM_OPTS
          value: -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dh2.bindAddress=127.0.0.1
        image: sonarqube:6.1
        imagePullPolicy: Always
        name: white-sonarqube 
        ports:
        - containerPort: 9092
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
